In [1]:
!pip install joblib

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [7]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs #iterartion
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with_bias:\n{X_with_bias}")
        

In [5]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [8]:
obj = Perceptron(eta = 0.01, epochs = 10 )

In [9]:
obj.eta

0.01

In [10]:
obj.epochs

10

In [11]:
obj.fit(X,y)

X_with_bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
