In [1]:
!pip install joblib

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [24]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs #iterartion
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z>0, 1, 0)
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with_bias:\n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch+1}")
            print("--"*10)
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after the forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updtaed weights after epoch:{epoch+1}/{self.epochs}:\n {self.weights}")
            print(f"##"*10)
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
        
    
        

In [25]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [26]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    return X,y

In [27]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA, epochs = EPOCHS)

model_or.fit(X,y)

X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after the forward pass: 
[0 1 0 1]
error: 
0    0
1    0
2    1
3    0
Name: y, dtype: int64
updtaed weights after epoch:1/10:
 [ 1.00016391e-01  4.32034875e-05 -9.99726351e-02]
####################
--------------------
for epoch >> 2
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updtaed weights after epoch:2/10:
 [1.00016391e-01 4.32034875e-05 2.73649318e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updtaed weights after epoch:3/10:
 [1.00016391e-01 4.32034875e-05 2.73649318e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error: 


In [23]:
model_or.predict(X=[[1,1]])

array([1])

In [28]:
AND = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}
df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [29]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_AND = Perceptron(eta = ETA, epochs = EPOCHS)

model_AND.fit(X,y)

X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after the forward pass: 
[0 1 0 1]
error: 
0    0
1   -1
2    0
3    0
Name: y, dtype: int64
updtaed weights after epoch:1/10:
 [ 5.70943910e-06 -9.99329020e-02  1.00027495e-01]
####################
--------------------
for epoch >> 2
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updtaed weights after epoch:2/10:
 [1.00005709e-01 6.70980131e-05 2.74947439e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updtaed weights after epoch:3/10:
 [ 5.70943910e-06 -9.99329020e-02  2.00027495e-01]
####################
--------------------
for epoch >> 4
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error

In [30]:
XOR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,0]
}
df_XOR = pd.DataFrame(AND)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [31]:
X, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_XOR = Perceptron(eta = ETA, epochs = EPOCHS)

model_XOR.fit(X,y)

X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updtaed weights after epoch:1/10:
 [-0.09995235 -0.09996245  0.20001144]
####################
--------------------
for epoch >> 2
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updtaed weights after epoch:2/10:
 [4.76529667e-05 3.75502944e-05 1.00011439e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updtaed weights after epoch:3/10:
 [1.00047653e-01 1.00037550e-01 1.14392160e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after the forward pass: 
[0 1 1 1]
error: 
0    0
1   -